First try
Dimashaman/symfony-test pull request #1
Opened 2021-09-08 10:26 UTC by Dimashaman

Lost of improvements

2021-09-08 22:41 UTC, pluseg requested changes

2021-09-08 22:41 UTC, pluseg commented on src/Service/CustomerImporter/Manager/CustomerManager.php
> +namespace App\Service\CustomerImporter\Manager;
Неверный путь. Во-первых, почему CustomerManager лежит в CustomerImporter? Ведь он не имеет никакой специфичной для процесса импорта кастомеров логики. Можем ли мы переиспользовать этот класс где-то в другом месте, где речь не об импорте, а просто о создании сущности? Да, конечно. Например, у нас будет страница на сайте (экшен в Контроллере) для создания нового кастомера вручную. Там мы также создадим CustomerDTO и засунем в этот метод processDTO. 

Поэтому давай положим класс в App\Service\EntityManager\ папку.

2021-09-08 22:41 UTC, pluseg commented on src/Service/CustomerImporter/Manager/CustomerManager.php
> +        }
Можно и так, но смущает, что дублируем вызов метода fillEntity. Можно так:
```
if (!$customer) {
    $customer = new Customer();
    $this->em->persist($customer);
}

$this->fillEntity($customerDTO, $customer);

return $customer;
```

После этого возникает вопрос — а нужно ли нам выделение отдельного метода fillEntity? Пока будет лучше от него избавиться, чтобы не усложнять, а его внутренности поместить прямо в processDTO().

2021-09-08 22:41 UTC, pluseg commented on src/Service/CustomerImporter/Manager/CustomerManager.php
> +    public function processDTO(CustomerDTO $customerDTO, ?Customer $existingCustomerEntity = null): Customer
Вот тут $existingCustomerEntity — излишне длинное название. Нам экономить на символах не нужно, но и бессмысленно удлинять названия не нужно — в длинных названиях можно запутаться. В общем, тут нужен баланс.

Во-первых, приписка entity совсем не нужна. $existingCustomer и так говорит о том, что это какой-то объект, представляющий кастомера. А что это за объект? Скорее всего Customer энтити. Поэтому слово Entity убираем.

Во-вторых, existing тут тоже не с руки. У нас тут не может быть другой entity, кроме существующей. Кроме того, в теории сюда могут передать энтити, которая была только что создана, но ещё не сохранена. Получается, что она не совсем $existing ещё. Лучше убрать и оставить просто `?Customer $customer = null`, из чего будет понятно, что либо будет передана сущность Customer, либо null. Existing или не existing нам не важно.

2021-09-08 22:41 UTC, pluseg commented on src/Service/CustomerImporter/Provider/RandomUserApiDataProvider.php
> +    const PARAMS = ['nat' => 'au', 'results' => '150', 'inc' => 'name, email, login, gender, location, phone'];
Массивы с несколькими ключами и значениями лучше хранить в multi-line формате, когда одна строка на один ключ. Так проще читать — сразу видно сколько разных ключей есть и проще найти нужный. Например:
```
private const QUERY_PARAMS = [
    'nat' => 'au',
    'results' => '150',
    'inc' => 'name, email, login, gender, location, phone',
];
```

Обрати внимание:
1. Мы всегда должны задавать область видимости — у методов, свойств и даже констант. Суть такая же, как указание типов — чем строже код, тем сложнее ошибиться в использовании. А кроме того, облегчает рефакторинг. Например, область видимости private сразу нам подсказывает, что эта константа или метод используется только в этом классе, а значит мы можем её видоизменять спокойно, не переживая, что где-то какой-то другой класс это использует и там всё сломается, если забудем переименовать.
2. Просто PARAMS — слишком общее. Лучше добавить, что это REQUEST_PARAMS или QUERY_PARAMS, так как мало какие ещё параметры могут быть у ДатаПровайдера.

2021-09-08 22:41 UTC, pluseg commented on src/Service/CustomerImporter/Provider/RandomUserApiDataProvider.php
> +    const API_URI = "https://randomuser.me/api";
Лучше всегда использовать одинарные кавычки. Это по кодстайлу Симфони. Странно, что php-cs-fixer у тебя не сработал на этом месте. Ты его на всю папку src запускал?

2021-09-08 22:41 UTC, pluseg commented on src/Service/CustomerImporter/Provider/RandomUserApiDataProvider.php
> +        $client = new Client([
Для облегчения чтения, можно назвать это $randomUserApiClient. Это даст подсказку, что именно за клиент тут создаётся.

2021-09-08 22:41 UTC, pluseg commented on src/Service/CustomerImporter/Provider/RandomUserApiDataProvider.php
> +        $resultBody = $result->getBody();
Можем добавить ->getBody выше после ->request()->getBody(), чтобы не создавать лишнюю промежуточную переменную и не занимать память. А лучше объединить с переменной ниже, всунув внутрь json_decode(). 
Единственным оправданием для отдельной переменной тут может быть, если мы хотим сделать проверку, что внутри json, что $resultBody не пустой и тп.

2021-09-08 22:41 UTC, pluseg commented on src/Service/CustomerImporter/Provider/RandomUserApiDataProvider.php
> +        $result = $client->request('GET', '', [
Это ещё не совсем $result, это только объект ответа — $response. В нём может быть ошибка 404, например, что ресурс не найден, или 403, что не хватает прав. Пока это только http response на http запрос. 

И хорошо бы чуть ниже проверить статус респонса 200, а иначе вернуть просто пустой массив (в будущем добавим выброс эксепшенов).

2021-09-08 22:41 UTC, pluseg commented on src/Service/CustomerImporter/Provider/RandomUserApiDataProvider.php
> +        $customers = json_decode($resultBody->getContents(), true)['results'];
Строка `$customers = [];` бессмысленная.
В строке с `['results']` хорошо бы проверить наличие этого ключа перед чтение. Можно сделать через оператор `??`:
```
$customers = json_decode($resultBody->getContents(), true)['results'] ?? [];
```

2021-09-08 22:41 UTC, pluseg commented on src/Service/CustomerImporter/Provider/RandomUserApiDataProvider.php
> +    private function parseToDTOs(array $customersData): array
Это не совсем parse, так как парсинг — это разбор строки и вычленение оттуда данных. Здесь же это маппинг/соответствие полей. Предлагаю назвать createCustomerDTO().
При этом я бы сам цикл оставил в основном метода, а этот метод отвечал бы только за превращение одного массив $customerData в одну CustomerDTO. Просто, чтобы разделить логику итерирования и обработки одной записи.

2021-09-08 22:41 UTC, pluseg commented on src/Service/CustomerImporter/Provider/RandomUserApiDataProvider.php
> +            $customerDTO->firstName = $customerData['name']['first'];
Мы должны быть оптимистами по жизни, но готовиться к плохому — добавь проверки, что все эти ключи в массиве есть. Что, если структура ответа API изменится? Всё попадает с непредсказуемыми ошибками.
Сделай проверки через `??`, с указанием справа дефолтного значения (например, null).

2021-09-08 22:41 UTC, pluseg commented on src/Service/CustomerImporter/Stats/CustomerImporterStats.php
> +namespace App\Service\CustomerImporter\Stats;
В принципе, ок, что положил в Stats. Но скорее всего у нас не будет много разных Stats внутри процесса импорта кастомеров, а значит у нас будет эта папка только для одного файла. Значит, можем обойтись без папки и положить файл прямо в App\Service\CustomerImporter.

2021-09-08 22:41 UTC, pluseg commented on src/Service/CustomerImporter.php
> +                $this->cm->processDTO($customerDTO, $existingCustomer);
Что такое cm? Уверен, что через неделю и сам не вспомнишь. Давай назовём полно и красиво — $this->customerManager.

2021-09-09 14:34 UTC, Dimashaman commented on src/Controller/CustomerController.php
>          return new JsonResponse($data);
сделал

2021-09-09 14:34 UTC, Dimashaman commented on src/Controller/CustomerController.php
>          $data = $repository->findAllShort();
Поправил

2021-09-09 14:35 UTC, Dimashaman commented on src/Entity/Customer.php
> +    private string $first_name;
Поправил

2021-09-09 14:35 UTC, Dimashaman commented on src/Entity/Customer.php
> +    private string $last_name;
Поправил

2021-09-09 14:36 UTC, Dimashaman commented on src/Entity/Customer.php
>      public function getId(): ?int
Сделано через Timestampable трейт

2021-09-09 14:37 UTC, Dimashaman commented on src/Service/CustomerImporter/Provider/RandomUserApiDataProvider.php
> +        $customers = json_decode($resultBody->getContents(), true)['results'];
Поправил!

2021-09-09 14:37 UTC, Dimashaman commented on src/Service/CustomerImporter/Provider/RandomUserApiDataProvider.php
> +    private function parseToDTOs(array $customersData): array
Поправил

2021-09-09 14:37 UTC, Dimashaman commented on src/Service/CustomerImporter/Provider/RandomUserApiDataProvider.php
> +            $customerDTO->firstName = $customerData['name']['first'];
Сделал

2021-09-09 14:37 UTC, Dimashaman commented on src/Service/CustomerImporter/Stats/CustomerImporterStats.php
> +namespace App\Service\CustomerImporter\Stats;
Сделал

2021-09-09 14:38 UTC, Dimashaman commented on src/Service/CustomerImporter.php
> +                $this->cm->processDTO($customerDTO, $existingCustomer);
Поправил

2021-09-09 14:53 UTC, Dimashaman commented on src/Service/CustomerImporter/Interface/ClientImporterDataProviderInterface.php
> +interface ClientImporterDataProviderInterface
Ппц :/ исправил

2021-09-10 01:34 UTC, Dimashaman commented on src/Service/CustomerImporter/DTO/CustomerDTO.php
> +    public string $phone;
#3 Вынес в отдельный Issue

2021-09-10 01:35 UTC, Dimashaman commented on src/Service/CustomerImporter/Provider/RandomUserApiDataProvider.php
> +        $result = $client->request('GET', '', [
#4 Вынес в отдельный Issue

2021-09-10 10:46 UTC, pluseg requested changes

2021-09-10 10:46 UTC, pluseg commented on config/packages/translation.yaml
> +#        providers:
Никогда не храни закомментированный код в репе. Даже если это временное решение, так как нужно понимать, что никто его не удалит, так как другие разработчики будут думать, что раз уж код оставили в репе, он для чего-то нужен. В итоге это как мусор, который со временем только увеличивается, но не уменьшается.

Если уж есть какой-то код, который нужно временно оставить, то стоит добавить текстовый комментарий выше: при каких условиях код нужно будет раскомментировать. Например, вставить ссылку на задачу или ещё что-то. По такому комментарию можно будет оценить, можно ли удалять этот коммент или нет.

2021-09-10 10:46 UTC, pluseg commented on src/Controller/CustomerController.php
> +        return new JsonResponse(['items' =>$pagination->getItems(), 'page' => $page, 'total' => $pagination->getTotalItemCount ()]);
Странный пробел между getTotalItemCount и (). Хоть это и кажется мелочью, но эти мелочи характеризуют наше отношение к деталям.

2021-09-10 10:46 UTC, pluseg commented on src/Controller/CustomerController.php
> +    public function index(Request $request, CustomerRepository $repository, PaginatorInterface $paginator): JsonResponse
Таки стоит назвать $customerRepository

2021-09-10 10:46 UTC, pluseg commented on src/Entity/Customer.php
> + * @UniqueEntity("email")
Это хорошо, что сделал. 

Дополнительно нужно добавить индексы. Как минимум, Unique index для email.

2021-09-10 10:46 UTC, pluseg commented on src/EventSubscriber/DoctrineExtensionSubscriber.php
> +    private $blameableListener;
Тебе не нужны эти листнеры, поэтому не стоит подключать. Иначе они просто замедлят обработку запроса.

2021-09-10 10:46 UTC, pluseg commented on src/Repository/CustomerRepository.php
>      // overriding find
Не следует переопределять дефолтные методы, это будет неожиданно для других разработчиков. Кроме того, а что, если тебе нужно будет получить полный объект по айди? Ты уже не сможешь воспользоваться этим методом.
Решение — создай отдельный метод с нужным функционалом.

2021-09-10 10:46 UTC, pluseg commented on src/Controller/CustomerController.php
> +        $page = $request->query->get('page', "1");
Можно использовать getInt() метод, чтобы точно получить int. Ну и хорошо бы проверить, что это положительное число.

2021-09-10 10:46 UTC, pluseg commented on src/Controller/CustomerController.php
> +            intval($page),
Лучше использовать тайпкастинг через (int). Это более современный и быстрый способ.

2021-09-10 10:46 UTC, pluseg commented on src/Repository/CustomerRepository.php
> +            ->select("c.id,(c.firstName + ' ' + c.lastName) as fullName, c.email, c.country");
В теории, можно сделать и так, чтобы получать не все данные, а только нужные для вывода. Но чаще всего такая оптимизация не сильно нужна, зато усложняет жизнь и поддержку кода, так как такие методы практически не переиспользуемы. 

Обычная практика — получать из базы целиковые Entity, а уже потом форматировать вывод либо в твиг-шаблонах, либо через Serializator, если речь про АПИ. Так мы отделяем логику получения данных и их вывода. В твоей реализации же, всё смешано. 
Проверка: 
1) представь, что нам в выводе нужно будет добавить дату createdAt. Для этого тебе придётся найти этот метод в репозитории и добавить это поле. 
2) Или представь, что у тебя поле поменяется название. Тебе придётся менять не только название полей в представлении, но и во всех запросах, что неудобно, так как любое изменение логики заставляет перетестить приложение, вдруг другой кусок кода тоже зависел от этого метода.
3) А что, если этот метод используется в двух-трёх местах и в каждом нужен свой набор данных? Будет делать три отдельных метода? Или в выборку добавим все поля?
4) следствие из пункта выше: а что, если после такого, мы убираем использование этого метода в одном из этих трёх мест. Нужно будет и убрать лишние, более не используемые поля в select? А где гарантия, что не уберём что-то лишнее? А если оставить, как есть, то уже получается несостыковка и запрашиваем больше, чем нужно. 

В общем, такая оптимизация — излишняя.

2021-09-10 10:46 UTC, pluseg commented on src/Service/CustomerImporter/Provider/RandomUserApiDataProvider.php
> +        } else {
Старайся всегда избегать else веток — https://refactoring.guru/ru/replace-nested-conditional-with-guard-clauses

Если ответ не 200, то мы можем сразу сделать return []. А потом продолжить уже без else ветки в основном потоке. Дело в том, что любой else усложняет чтение логики — нам приходится держать в уме, в каком именно мы сейчас условии и как это влияет на код. Сравни:

1) Сейчас мы читаем этот if/else, он простой. Но дальше начинается другая логика — цикл по $customersResponseData, нам приходится возвращаться глазами выше, чтобы понять, чему эта переменная равна и как задаётся. Приходится держать в голове оба кейса и читать дальше (мы ещё не знаем, что дальше эта переменная не используется, поэтому приходится держать это в памяти).
2) представь логику:

```
if ($response->getStatusCode() !== 200) {
    return [];
}

$customersResponseData = json_decode($response->getBody()->getContents(), true)['results'] ?? [];
foreach ($customersResponseData as $customer) {
    ...
}
```
В этом случае мы сразу отсекаем кейс с неправильным кодом и не держим его в памяти, а дальше код становится снова последовательным и понятным.

2021-09-10 10:46 UTC, pluseg commented on src/Service/CustomerImporter/Provider/RandomUserApiDataProvider.php
> +        'results' => '150',
Хорошо бы это число передавать из консольной команды, а не хардкодить.

2021-09-10 12:41 UTC, Dimashaman commented on src/Entity/Customer.php
> + * @UniqueEntity("email")
`    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE UNIQUE INDEX UNIQ_81398E09E7927C74 ON customer (email)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX UNIQ_81398E09E7927C74 ON customer');
    }
}
`  в миграции Version20210904023150.php сделал

2021-09-12 23:16 UTC, Dimashaman commented on src/Service/CustomerImporter/Provider/RandomUserApiDataProvider.php
> +        'results' => '150',
Забыл спросить как это грамотно сделать с учетом возможных различных Provider'ов :(

2021-09-15 19:37 UTC, pluseg requested changes

2021-09-15 19:37 UTC, pluseg commented on src/Controller/CustomerController.php
> +            15
Это magic integer. Мы можем только догадываться, что это размер страницы. Чтобы было проще читать, давай вынесем в константу `private const ENTITIES_PER_PAGE = 15;`.

2021-09-15 19:37 UTC, pluseg commented on src/Controller/CustomerController.php
> +        $customersResource = $normalizer->normalize($pagination->getItems(), null, ['groups' => 'index']);
О, это хорошо, что и нормалайзер заюзал. Но по идее, тебе тут нужен Serializer, он уже внутри себя и нормалайзер вызовет, и приведёт к нужному типу данные ниже (к json в данном случае).

2021-09-15 19:37 UTC, pluseg commented on src/Controller/CustomerController.php
> +        $customer = $customerRepository->findForShow($id);
Мы это обсуждали — нет нужды создавать уникальные методы на каждый чих, так как переиспользовать их сложно в силу запрашиваемых данных. Проще получить entity через ->find($id), а потом в нормалайзере/сериалайзере сделать виртуальное поле (через геттер) для fullName.

2021-09-15 19:37 UTC, pluseg commented on src/Entity/Customer.php
> + * @UniqueEntity("email")
В итоге не сделано? Не нахожу это в миграциях. Уточню, что на базу данных мы всегда влияем через изменения entity, ничего вручную в миграции не добавляем.

Вот пример для entity:
```
 * @ORM\Table(
 *     uniqueConstraints={
 *         @ORM\UniqueConstraint(name="customer_unique_email", columns={"email"})
 *     }
 * )
```

2021-09-15 19:37 UTC, pluseg commented on src/Entity/Customer.php
> + * @UniqueEntity("email")
Воможно, `unique=true` тоже достаточно, но ты просто не создал миграцию через `bin/console make:migration`.

2021-09-15 19:37 UTC, pluseg commented on src/Message/CustomerImporterTask.php
> +    public function __construct(CustomerDTO $customerDto, ?Customer $existingCustomer)
Мы не должны слать в мессаджах всю Энтити. Я тебе уже про это писал, но если не понятно, то почитай объяснение в документации.

2021-09-15 19:37 UTC, pluseg commented on src/Repository/CustomerRepository.php
> +    public function findAllForIndex() : QueryBuilder
Мы этот метод где-то используем? Что за findAllForIndex? Для какого индекса?

2021-09-15 19:37 UTC, pluseg commented on src/Service/CustomerImporter.php
> +            $existingCustomer = $this->entityManager->getRepository(Customer::class)->findOneBy(['email' => $customerDTO->email]);
С точки зрения производительности, лучше это вынести в Handler. Да, тогда не получится считать $existingCustomersCount, но тут мы должны сделать выбор — насколько нам это нужно и можем ли мы поступиться перформансом ради этого.

2021-09-15 19:37 UTC, pluseg commented on src/Service/CustomerImporter/Provider/RandomUserApiDataProvider.php
> +        'results' => '150',
Вынести в интерфейс, и каждый провайдер будет его использовать по-своему.

2021-09-15 19:37 UTC, pluseg commented on src/Service/EntityManager/CustomerManager.php
> +        // if (!$this->entityManager->isOpen()) {
Commented code detected!

2021-09-15 19:37 UTC, pluseg commented on tests/CustomerImporterTest.php
> +    public function testSomething(): void
Бесполезный тест для хранения в репозитории.

2021-09-15 19:37 UTC, pluseg commented on tests/CustomerImporterTest.php
> +    public function a_customer_record_can_be_created_in_the_databases() : void
Мы должны называть методы как testMethodName(), где MethodName — название оригинального тестируемеого метода из CustomerImporter (мы же здесь пишем тесты для него).

2021-09-15 19:37 UTC, pluseg commented on tests/CustomerImporterTest.php
> +        $this->assertEquals('John', $customerRecord->getFirstName());
А что мы здесь тестим? Что просто persist новой сущности работает? Это работает априори, это тестить не нужно.

2021-09-15 19:37 UTC, pluseg commented on tests/CustomerImporterTest.php
> +        $command = $application->find('app:customers-import');
Работоспособность команды проверять не надо. Вместо этого, надо проверить работоспособность метода CustomerImporter::import(), подкидывая в конструктор CustomerImporter разные mock для CustomerDataProvider. Этот мок должен возвращать массив CustomerDTO, которые мы сами определим в тесте. А потом надо проверить, что после импорта во-первых, возвращается правильный объект с ImporterStats, во-вторых, что в базе появляются соответствующие энтити кастомеров.

2021-09-15 19:37 UTC, pluseg commented on tests/CustomerImporterTest.php
> +        dump($customerRecords);
Дебаг-код нельзя хранить в репозитории, это грязь.

2021-09-16 00:41 UTC, Dimashaman commented on src/Controller/CustomerController.php
> +     * @param CustomerRepository<Customer> $customerRepository
Да

2021-09-27 10:10 UTC, pluseg requested changes

2021-09-27 10:10 UTC, pluseg commented on tests/CustomerImporterTest.php
> +        $this->assertInstanceOf(ImporterStats::class, $stats);
Тест что-то тестирует, но пока мало пользы.
Мы обсуждали, что нужно мокать только $customerDataProvider, а остальные можно использовать реальные сервисы. При этом мы должны будем переопределить метод getCustomersData() и чекать, что будет возвращаться в $stats. Например, мы можем в методе getCustomersData() возвращать невалидные данные или в не той структуре, что ожидаем от АПИ и проверить, как код import() это отрабатывает. Будут ли такие строки учтены в ошибках внутри ImporterStats?

2021-09-28 06:40 UTC, Dimashaman commented on src/Repository/CustomerRepository.php
> +    public function customersQueryBuilder() : QueryBuilder
С QueryBuilder'ом работает пагинатор в контроллере, поэтому он возвращается

2021-10-02 00:59 UTC, merged